### ISSUE TITLE
[BUG] Probleme mit XMLTYPE und OJDBC

### ISSUE THREAD

**Issue by h9h** [karalus/esb0#6]
Bei der Übergabe von Calls aus der Datapower,  wird ein OJDBC Treiber beim XMLTyp ein sog. "SAXResult" verwendet.

In der Version 1.9.0 des [esb0](https://github.com/karalus/esb0/commits/master) tritt dabei ein Fehler auf, welches dazu führt. Dass die Zuordnung des Namespaces fehlerhaft ist. Statt z.B. der Namespace n12 verwendet wird. Wird das Attribut mit n14 gekennzeichnet.

Ein Bugfix zu diesem Fehler wurde schon mal mit den Commit 8ed3d5de3f6b8d70091a3cf744dc6c8772194267 (Bugfix: Workaround OJDBC bug) behoben. Nach der Überarbeitung der Klasse [JDBCConnection.java](https://github.com/karalus/esb0/blob/master/src/main/java/com/artofarc/esb/jdbc/JDBCConnection.java) tritt der Fehler wieder auf.

 

Lösen kann man das Problem, indem man den Oracle-SAX-Transformer dazwischen schaltet und die von Saxon/Xerces produzierten SAX-Events auf die proprietäre Sichtweise von Oracle konvertiert.

**Comment by karalus** [comment]
Got no further input on this issue. Cannot reproduce.
